name: notes_hive_getx
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  # sdk: '>=3.5.0-311.0.dev <4.0.0'
  sdk: ^3.6.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  hive_generator: ^2.0.1
  screenshot: ^3.0.0
  # image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.1
  intl: ^0.19.0
  scroll_screenshot: ^0.0.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0


flutter:

  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
